default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost

development: &development
  <<: *default
  database: batusay_development

test: &test
  <<: *default
  database: batusay_test

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
