# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b1216bf61f60f56e15044059ec4bf0ad5f7dfa847aed0684f31843e55a8a11fcbccc2b9cffb3d84b1b63b094373dd71df3363fd63abe38d88fb5fa4f89935ea
  spotify_client: e16acd3a7ef344789b1a6cac6c2c8881
  spotify_secret: 70e0aefbaf15487d9604a956f60aa86c
  facebook_key: 1955929047972256
  facebook_secret: cc43cad4b39458709b7287973f7d9ca0
  app_url: http://localhost:3786

test:
  secret_key_base: 663ba2fe62172845bf5def9fb3980d6d09cf2fad48b900b7f606f955ca272bc2e9b1f978902da7bdde265aa7c0ea4d6a20bc4e09ea2768c62285f6f8f8e0e467
  spotify_client: e16acd3a7ef344789b1a6cac6c2c8881
  spotify_secret: 70e0aefbaf15487d9604a956f60aa86c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  spotify_client: <%= ENV["SPOTIFY_CLIENT"] %>
  spotify_secret: <%= ENV["SPOTIFY_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  app_url: https://batusay.herokuapp.com
